Nop.Plugin.DiscountRules.BillingCountry/Models/RequirementModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.DiscountRules.BillingCountry.Models
{
    public class RequirementModel
    {
        public RequirementModel()
        {
            AvailableCountries = new List<SelectListItem>();
        }

        [NopResourceDisplayName("Plugins.DiscountRules.BillingCountry.Fields.Country")]
        public int CountryId { get; set; }

        public int DiscountId { get; set; }

        public int RequirementId { get; set; }

        public IList<SelectListItem> AvailableCountries { get; set; }
    }
}

Nop.Plugin.DiscountRules.BillingCountry/Controllers/DiscountRulesBillingCountryController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Discounts;
using Nop.Plugin.DiscountRules.BillingCountry.Models;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Discounts;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace Nop.Plugin.DiscountRules.BillingCountry.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public class DiscountRulesBillingCountryController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly IDiscountService _discountService;
        private readonly ICountryService _countryService;
        private readonly ISettingService _settingService;
        private readonly IPermissionService _permissionService;

        #endregion

        #region Ctor

        public DiscountRulesBillingCountryController(ILocalizationService localizationService, 
            IDiscountService discountService, 
            ICountryService countryService,
            ISettingService settingService, 
            IPermissionService permissionService)
        {
            this._localizationService = localizationService;
            this._discountService = discountService;
            this._countryService = countryService;
            this._settingService = settingService;
            this._permissionService = permissionService;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure(int discountId, int? discountRequirementId)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageDiscounts))
                return Content("Access denied");

            var discount = await _discountService.GetDiscountByIdAsync(discountId);
            if (discount == null)
                throw new ArgumentException("Discount could not be loaded");

            DiscountRequirement discountRequirement = null;
            if (discountRequirementId.HasValue)
            {
                discountRequirement = await _discountService.GetDiscountRequirementByIdAsync(discountRequirementId.Value);
                if (discountRequirement == null)
                    return Content("Failed to load requirement.");
            }

            var billingCountryId = await _settingService.GetSettingByKeyAsync<int>($"DiscountRequirement.BillingCountry-{discountRequirementId ?? 0}");

            var model = new RequirementModel
            {
                RequirementId = discountRequirementId ?? 0,
                DiscountId = discountId,
                CountryId = billingCountryId
            };

            //countries
            model.AvailableCountries.Add(new SelectListItem() { Text = await _localizationService.GetResourceAsync("Plugins.DiscountRules.BillingCountry.Fields.SelectCountry"), Value = "0" });
            foreach (var c in await _countryService.GetAllCountriesAsync(showHidden: true))
                model.AvailableCountries.Add(new SelectListItem() { Text = c.Name, Value = c.Id.ToString(), Selected = discountRequirement != null && c.Id == billingCountryId });

            //add a prefix
            ViewData.TemplateInfo.HtmlFieldPrefix = $"DiscountRulesBillingCountry{discountRequirementId?.ToString() ?? "0"}";

            return View("~/Plugins/DiscountRules.BillingCountry/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(int discountId, int? discountRequirementId, int countryId)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageDiscounts))
                return Content("Access denied");

            var discount = await _discountService.GetDiscountByIdAsync(discountId);
            if (discount == null)
                throw new ArgumentException("Discount could not be loaded");

            DiscountRequirement discountRequirement = null;
            if (discountRequirementId.HasValue)
                discountRequirement = await _discountService.GetDiscountRequirementByIdAsync(discountRequirementId.Value);

            if (discountRequirement != null)
            {
                //update existing rule
                await _settingService.SetSettingAsync($"DiscountRequirement.BillingCountry-{discountRequirement.Id}", countryId);
            }
            else
            {
                //save new rule
                discountRequirement = new DiscountRequirement()
                {
                    DiscountId = discount.Id,
                    DiscountRequirementRuleSystemName = "DiscountRequirement.BillingCountryIs"
                };
                await _discountService.InsertDiscountRequirementAsync(discountRequirement);
                
                await _settingService.SetSettingAsync($"DiscountRequirement.BillingCountry-{discountRequirement.Id}", countryId);
            }

            return Json(new { Result = true, NewRequirementId = discountRequirement.Id });
        }

        #endregion
    }
}

Nop.Plugin.DiscountRules.BillingCountry/Views/Configure.cshtml
@{
    Layout = "";
}
@model Nop.Plugin.DiscountRules.BillingCountry.Models.RequirementModel

    <script type="text/javascript">
        $(document).ready(function () {
            $('#savebillingcountryrequirement@(Model.RequirementId)').click(function () {
                var countryId = $("#@Html.IdFor(model => model.CountryId)").val();
                var discountId = @Model.DiscountId;
                var requirementId = @Model.RequirementId;
                
                var postData = {
                    discountId: discountId, 
                    discountRequirementId: requirementId, 
                    countryId: countryId
                };
                addAntiForgeryToken(postData);

                $.ajax({
                    cache:false,
                    type: "POST",
                    url: "@(Url.Action("Configure", "DiscountRulesBillingCountry"))",
                    data: postData,
                    success: function (data) {
                         $('#pnl-save-requirement-result@(Model.RequirementId)').fadeIn("slow").delay(1000).fadeOut("slow");
                         //notify parent if it's a new requirement
                         @if (Model.RequirementId == 0)
                         {
                            <text>$("#discountRequirementContainer").trigger('nopnewdiscountruleadded', [data.NewRequirementId]);</text>
                         }
                    },
                    error:function (xhr, ajaxOptions, thrownError){
                        alert('@Html.Raw(JavaScriptEncoder.Default.Encode(T("Admin.Promotions.Discounts.Requirements.FailedToSave").Text))');
                    }  
                });
            });
        });
    </script>

    <div class="form-group row">
        <div class="col-md-3 requirement-label-col">
            <nop-label asp-for="CountryId" />
        </div>
        <div class="col-md-9 requirement-data-col">
            <div class="requirement-data-input">
                <nop-select asp-for="CountryId" asp-items="Model.AvailableCountries" />
            </div>
            <div class="requirement-data-buttons">
                <input type="button" id="savebillingcountryrequirement@(Model.RequirementId)" class="btn btn-primary" value="@T("Admin.Common.Save")" />
            </div>
        </div>
    </div>
<div class="form-group row">
    <div class="col-md-offset-3 col-md-9 requirement-messages-col">
        <div id="pnl-save-requirement-result@(Model.RequirementId)" class="text-green margin-t-5" style="display: none;">
            @T("Admin.Promotions.Discounts.Requirements.Saved")
        </div>
    </div>
</div>